### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by cyj1208** [hudscomdz/IMS2Trans#3]
作者，您好。在运行您的代码时，出现了以下报错，应该如何解决？Traceback (most recent call last):
  File "/root/autodl-tmp/IMS2Trans-main/train.py", line 387, in <module>
    main()
  File "/root/autodl-tmp/IMS2Trans-main/train.py", line 256, in main
    fuse_pred1, dis_preds1, prm_preds1 = model(new_x1, his_mask)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/IMS2Trans-main/ims2trans.py", line 1404, in forward
    t1_x1, t1_x2, t1_x3, t1_x4, t1_x5 = self.swinEncoder(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/IMS2Trans-main/ims2trans.py", line 898, in forward
    x1 = self.layers1[0](x0.contiguous(), self.mt1_token1)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/IMS2Trans-main/ims2trans.py", line 692, in forward
    x = blk(x, attn_mask, m_token)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/IMS2Trans-main/ims2trans.py", line 605, in forward
    x = self.forward_part1(x, mask_matrix, m_token)
  File "/root/autodl-tmp/IMS2Trans-main/ims2trans.py", line 571, in forward_part1
    attn_windows = self.attn(x_windows, mask=attn_mask)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/IMS2Trans-main/ims2trans.py", line 443, in forward
    attn = attn + relative_position_bias.unsqueeze(0)
RuntimeError: CUDA out of memory. Tried to allocate 1.32 GiB (GPU 0; 23.64 GiB total capacity; 20.15 GiB already allocated; 841.69 MiB free; 20.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Process finished with exit code 1

**Comment by pyp666** [comment]
你好，问题解决了吗
